server:
  port: 10038
  servlet:
    context-path: /api
spring:
  cloud:
    gateway:
      routes:
        - id: travel-route
          uri: http://localhost:9090/api/travel
          predicates:
            - Path=/api/travel/{segment}

        - id: flight-route
          uri: http://localhost:9091/api/flight
          predicates:
            - Path=/api/flight/{segment}

        - id: hotel-route
          uri: http://localhost:9092/api/hotel
          predicates:
            - Path=/api/hotel/{segment}

        - id: taxi-route
          uri: http://localhost:9093/api/taxi
          predicates:
            - Path=/api/taxi/{segment}

logging:
  level:
    root: DEBUG