version: '3.7'
#networks:
#  application:
#    driver: bridge
services:
  sbgatewaysv:
    image: travelapp/sbgatewaysv:latest
    container_name: sbgatewaysv
    build:
      context: ../travel-gateway
    ports:
      - "8080:8080"
    depends_on:
      - sbtravelsv
    restart: always
    environment:
      - xms=256m
      - xmx=256m
  sbtravelsv:
    image: travelapp/sbtravelsv:latest
    container_name: sbtravelsv
    build:
      context: ../travel-booking-app
    restart: always
    depends_on:
      - coordinator
      - sbflightsv
      - sbhotelsv
      - sbtaxisv
    environment:
      - xms=256m
      - xmx=256m
      - FLIGHT_API=http://sbflightsv/api/flight/book
      - HOTEL_API=http://sbhotelsv/api/hotel/book
      - TAXI_API=http://sbtaxisv/api/taxi/book
      - SERVER_PORT=80
      - LOGGING_LEVEL_ROOT=DEBUG
  sbflightsv:
    image: travelapp/sbflightsv:latest
    container_name: sbflightsv
    build:
      context: ../flight-booking-service
    restart: always
    depends_on:
      - coordinator
    environment:
      - xms=256m
      - xmx=256m
      - SERVER_PORT=80
  sbhotelsv:
    image: travelapp/sbfhotelsv:latest
    container_name: sbhotelsv
    build:
      context: ../hotel-booking-service
    restart: always
    depends_on:
      - coordinator
    environment:
      - xms=256m
      - xmx=256m
      - SERVER_PORT=80
  sbtaxisv:
    image: travelapp/sbtaxisv:latest
    container_name: sbtaxisv
    build:
      context: ../taxi-booking-service
    restart: always
    depends_on:
      - coordinator
    environment:
      - xms=256m
      - xmx=256m
      - SERVER_PORT=80
  coordinator:
    image: quay.io/jbosstm/lra-coordinator:latest
    environment:
      LRA_HTTP_PORT: 80
