server:
  port: 9093
#  servlet:
#    context-path: /api
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
logging:
  level:
    org:
      apache:
        camel: DEBUG
camel:
  lra:
    enabled: true
    coordinator-url: http://localhost:8080
    local-participant-url: http://localhost:9093/api
  servlet:
    mapping:
      context-path: /api/*
      enabled: true
  springboot:
    main-run-controller: true